import os

def generate_runtime(output_dir):
    os.makedirs(output_dir, exist_ok=True)
    
    header = [
        '#ifndef L_RUNTIME_H',
        '#define L_RUNTIME_H',
        '#include <stdio.h>',
        '#include <stdlib.h>',
        '#include <string.h>',
        '',
        'typedef struct LObject {',
        '    enum { L_INT, L_FLOAT, L_STRING } type;',
        '    union {',
        '        int int_val;',
        '        double float_val;',
        '        char* string_val;',
        '    };',
        '} LObject;',
        '',
        'LObject* l_new_int(int value);',
        'LObject* l_new_float(double value);',
        'LObject* l_new_string(const char* value);',
        'void l_free(LObject* obj);',
        'void l_print(LObject* obj);',
        'void l_newline();',
        'LObject* l_add(LObject* a, LObject* b);',
        'LObject* l_sub(LObject* a, LObject* b);',
        'LObject* l_mul(LObject* a, LObject* b);',
        'LObject* l_div(LObject* a, LObject* b);',
        '#endif'
    ]
    
    impl = [
        '#include "l_runtime.h"',
        '',
        'LObject* l_new_int(int value) {',
        '    LObject* obj = malloc(sizeof(LObject));',
        '    obj->type = L_INT;',
        '    obj->int_val = value;',
        '    return obj;',
        '}',
        '',
        'LObject* l_new_float(double value) {',
        '    LObject* obj = malloc(sizeof(LObject));',
        '    obj->type = L_FLOAT;',
        '    obj->float_val = value;',
        '    return obj;',
        '}',
        '',
        'LObject* l_new_string(const char* value) {',
        '    LObject* obj = malloc(sizeof(LObject));',
        '    obj->type = L_STRING;',
        '    obj->string_val = strdup(value);',
        '    return obj;',
        '}',
        '',
        'void l_free(LObject* obj) {',
        '    if (obj) {',
        '        if (obj->type == L_STRING) free(obj->string_val);',
        '        free(obj);',
        '    }',
        '}',
        '',
        'void l_print(LObject* obj) {',
        '    if (!obj) return;',
        '    switch (obj->type) {',
        '        case L_INT: printf("%d", obj->int_val); break;',
        '        case L_FLOAT: printf("%.2f", obj->float_val); break;',
        '        case L_STRING: printf("%s", obj->string_val); break;',
        '    }',
        '}',
        '',
        'void l_newline() { printf("\\n"); }',
        '',
        'LObject* l_add(LObject* a, LObject* b) {',
        '    if (a->type != L_INT || b->type != L_INT) {',
        '        fprintf(stderr, "Type error in add\\n");',
        '        exit(1);',
        '    }',
        '    return l_new_int(a->int_val + b->int_val);',
        '}',
        '',
        'LObject* l_sub(LObject* a, LObject* b) {',
        '    if (a->type != L_INT || b->type != L_INT) {',
        '        fprintf(stderr, "Type error in sub\\n");',
        '        exit(1);',
        '    }',
        '    return l_new_int(a->int_val - b->int_val);',
        '}',
        '',
        'LObject* l_mul(LObject* a, LObject* b) {',
        '    if (a->type != L_INT || b->type != L_INT) {',
        '        fprintf(stderr, "Type error in mul\\n");',
        '        exit(1);',
        '    }',
        '    return l_new_int(a->int_val * b->int_val);',
        '}',
        '',
        'LObject* l_div(LObject* a, LObject* b) {',
        '    if (a->type != L_INT || b->type != L_INT || b->int_val == 0) {',
        '        fprintf(stderr, "Type error or division by zero\\n");',
        '        exit(1);',
        '    }',
        '    return l_new_int(a->int_val / b->int_val);',
        '}'
    ]

    with open(os.path.join(output_dir, 'l_runtime.h'), 'w') as f:
        f.write('\n'.join(header))
    
    with open(os.path.join(output_dir, 'l_runtime.c'), 'w') as f:
        f.write('\n'.join(impl))